parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react-router-dom"),s=require("react/jsx-runtime");const r=({name:r,animal:t,breed:i,images:a,location:n,id:l})=>{let c="http://pets-images.dev-apis.com/pets/none.jpg";return a.length&&(c=a[0]),(0,s.jsxs)(e.Link,{to:`/details/${l}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:c,alt:r})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:r}),(0,s.jsx)("h2",{children:`${t} - ${i} - ${n}`})]})]})};var t=r;exports.default=t;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(a=>(0,t.jsx)(e.default,{name:a.name,animal:a.animal,breed:a.breed,images:a.images,location:`${a.city}, ${a.state}`,id:a.id},a.id)):(0,t.jsx)("h2",{children:"No pets found."})});var s=r;exports.default=s;
},{"./Pet":"qepC"}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=s(require("./ThemeContext")),a=s(require("./useBreedList")),r=s(require("./Results")),l=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}const n=["bird","cat","dog","rabbit","reptile"],i=()=>{const[s,i]=(0,e.useState)(""),[o,u]=(0,e.useState)(""),[c,d]=(0,e.useState)(""),[h,p]=(0,e.useState)([]),[x]=(0,a.default)(o),[v,j]=(0,e.useContext)(t.default);async function m(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${o}&location=${s}&breed=${c}`),t=await e.json();p(t.pets)}return(0,e.useEffect)(()=>{m()},[]),(0,l.jsxs)("div",{className:"search-params",children:[(0,l.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,l.jsxs)("label",{htmlFor:"location",children:["Location",(0,l.jsx)("input",{id:"location",onChange:e=>i(e.target.value),value:s,placeholder:"Location"})]}),(0,l.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,l.jsxs)("select",{id:"animal",value:o,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,l.jsx)("option",{}),n.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,l.jsxs)("select",{id:"breed",value:c,onChange:e=>d(e.target.value),onBlur:e=>d(e.target.value),children:[(0,l.jsx)("option",{}),x.map(e=>(0,l.jsx)("option",{value:e,children:e},e))]})]}),(0,l.jsxs)("label",{htmlFor:"theme",children:["Theme",(0,l.jsxs)("select",{value:v,onChange:e=>j(e.target.value),onBlur:e=>j(e.target.value),children:[(0,l.jsx)("option",{value:"darkblue",children:"Dark Blue"}),(0,l.jsx)("option",{value:"peru",children:"Peru"}),(0,l.jsx)("option",{value:"chartreuse",children:"Chartreuse"}),(0,l.jsx)("option",{value:"mediumorchid",children:"Medium Orchid"})]})]}),(0,l.jsx)("button",{style:{backgroundColor:v},children:"Submit"})]}),(0,l.jsx)(r.default,{pets:h})]})};var o=i;exports.default=o;
},{"./ThemeContext":"2tnM","./useBreedList":"/HkA","./Results":"r5l1"}],"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=s(require("@babel/runtime/helpers/defineProperty")),t=require("react"),a=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}class r extends t.Component{constructor(...t){super(...t),(0,e.default)(this,"state",{active:0}),(0,e.default)(this,"handleIndexClick",e=>{this.setState({active:+e.target.dataset.index})})}render(){const{active:e}=this.state,{images:t}=this.props;return(0,a.jsxs)("div",{className:"carousel",children:[(0,a.jsx)("img",{src:t[e],alt:"animal"}),(0,a.jsx)("div",{className:"carousel-smaller",children:t.map((t,s)=>(0,a.jsx)("img",{src:t,"data-index":s,onClick:this.handleIndexClick,className:s===e?"active":"",alt:"animal thumbnail"},t))})]})}}(0,e.default)(r,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var i=r;exports.default=i;
},{}],"mD05":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=s(require("@babel/runtime/helpers/defineProperty")),r=require("react"),t=require("react-router-dom"),o=require("react/jsx-runtime");function s(e){return e&&e.__esModule?e:{default:e}}class i extends r.Component{constructor(...r){super(...r),(0,e.default)(this,"state",{hasError:!1,redirect:!1})}static getDerivedStateFromError(){return{hasError:!0}}componentDidCatch(e,r){console.error("ErrorBoundary caught an error",e,r),setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,o.jsx)(t.Redirect,{to:"/"}):this.state.hasError?(0,o.jsxs)("h2",{children:["This listing has an error. ",(0,o.jsx)(t.Link,{to:"/",children:"Click here"})," to go back to the homepage or wait five seconds."]}):this.props.children}}var a=i;exports.default=a;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=h;var e=l(require("@babel/runtime/helpers/defineProperty")),t=require("react"),s=require("react-router-dom"),o=l(require("./Carousel")),r=l(require("./ErrorBoundary")),i=l(require("./ThemeContext")),a=l(require("./Modal")),d=require("react/jsx-runtime");function l(e){return e&&e.__esModule?e:{default:e}}class n extends t.Component{constructor(...t){super(...t),(0,e.default)(this,"state",{loading:!0,showModal:!1}),(0,e.default)(this,"toggleModal",()=>this.setState({showModal:!this.state.showModal})),(0,e.default)(this,"adopt",()=>window.location="http://bit.ly/pet-adopt")}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}render(){if(this.state.loading)return(0,d.jsx)("h2",{children:"Loading..."});const{animal:e,breed:t,city:s,state:r,description:l,name:n,images:u,showModal:h}=this.state;return(0,d.jsxs)("div",{className:"details",children:[(0,d.jsx)(o.default,{images:u}),(0,d.jsxs)("div",{children:[(0,d.jsx)("h1",{children:n}),(0,d.jsxs)("h2",{children:[e," - ",t," - ",s,", ",r]}),(0,d.jsx)(i.default.Consumer,{children:([e])=>(0,d.jsxs)("button",{onClick:this.toggleModal,style:{backgroundColor:e},children:["Adopt ",n]})}),(0,d.jsx)("p",{children:l}),h?(0,d.jsx)(a.default,{children:(0,d.jsxs)("div",{children:[(0,d.jsxs)("h2",{children:["Would you like to adopt ",n,"?"]}),(0,d.jsxs)("div",{className:"buttons",children:[(0,d.jsx)("button",{onClick:this.adopt,style:{backgroundColor:this.props.theme},children:"Yes"}),(0,d.jsx)("button",{onClick:this.toggleModal,style:{backgroundColor:this.props.theme},children:"No"})]})]})}):null]})]})}}const u=(0,s.withRouter)(n);function h(){return(0,d.jsx)(r.default,{children:(0,d.jsx)(u,{})})}
},{"./Carousel":"Ztkr","./ErrorBoundary":"mD05","./ThemeContext":"2tnM","./Modal":"KnKP"}],"eBcb":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("./SearchParams")),d=u(require("./Details")),i=u(require("./ThemeContext")),s=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("darkblue");return(0,s.jsx)(e.StrictMode,{children:(0,s.jsx)(i.default.Provider,{value:u,children:(0,s.jsxs)("div",{children:[(0,s.jsx)("header",{children:(0,s.jsx)(r.Link,{to:"/",children:(0,s.jsx)("h1",{children:"Adopt Me!"})})}),(0,s.jsxs)(r.Switch,{children:[(0,s.jsx)(r.Route,{path:"/details/:id",children:(0,s.jsx)(d.default,{})}),(0,s.jsx)(r.Route,{path:"/",children:(0,s.jsx)(t.default,{})})]})]})})})};var l=a;exports.default=l;
},{"./SearchParams":"n0tu","./Details":"C/Dc","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=u(require("express")),t=require("react-dom/server"),r=require("react-router-dom"),s=u(require("fs")),i=u(require("../src/App")),n=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const o=process.env.port||3e3,d=s.default.readFileSync("dist/index.html").toString(),l=d.split("not rendered"),c=(0,e.default)();c.use("/dist",e.default.static("dist")),c.use((e,s)=>{s.write(l[0]);const u={},o=(0,n.jsx)(r.StaticRouter,{url:e.url,context:u,children:(0,n.jsx)(i.default,{})}),d=(0,t.renderToNodeStream)(o);d.pipe(s,{end:!1}),d.on("end",()=>{s.status(u||200),s.write(l[1]),s.end()})}),console.log(`Listening on http://localhost:${o}`),c.listen(o);
},{"../src/App":"eBcb"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map